version: '2'
services:

  # The Application
  app:
    container_name: app_laravel_api
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    container_name: web_laravel_api
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8003:80

  # The Database
  database:
    container_name: database_laravel_api
    image: mysql:latest
    environment:
      - "MYSQL_DATABASE=lv_api"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=123456"
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
        - "3310:3306"
    restart: always
    volumes:
      - vol-laravel-api:/var/lib/mysql

volumes:
  vol-laravel-api:
